services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb+srv://purple:pdfl3ydpewMD9s9m@autoagentevalutationclu.jnz84ae.mongodb.net/?retryWrites=true&w=majority&appName=autoAgentEvalutationCluster
      - MONGO_DB=auto_agent_evaluation  
      - SQL_URI=mysql+mysqlconnector://root:thapa55word@sql:3306/auto_agent_evaluation
      - POSTGRE_URI=postgresql://neondb_owner:npg_UrPqYpS5xHm0@ep-shy-scene-ae75eee2-pooler.c-2.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
    depends_on:
      - mongo
      - sql

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  sql:
    image: mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=thapa55word
      - MYSQL_DATABASE=auto_agent_evaluation


