services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb+srv://purple:pdfl3ydpewMD9s9m@autoagentevalutationclu.jnz84ae.mongodb.net/?retryWrites=true&w=majority&appName=autoAgentEvalutationCluster
      - SQL_URI=mysql+mysqlconnector://root:thapa55word@sql:3306/auto_agent_evaluation
    depends_on:
      - mongo
      - sql

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  sql:
    image: mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=thapa55word
      - MYSQL_DATABASE=auto_agent_evaluation

  seed:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo
    command: ["python", "seed_roles.py"]